name = "Client"
author = "circle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07750ad10f216acbfcccc642b0a9910d36ee68498340fe81cce0669f2ecdc713"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
