name = "Circle's Pack"
author = "Circle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8393fe04fdd0629e9f170e718382affc16027308aa8cdcb592658718f23a35c"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.3"
