name = "Circle's Pack"
author = "Circle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8eb7b4c2cbe24be5108494ec1435e1bd2beb652cf01791d8f1697cf450790a42"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.3"
