name = "Circle's Pack"
author = "Circle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5eb5f027a3a18a1f3fae2ab92d49592d358ff6367d1f918701599a4833b8a5b"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.3"
