name = "Circle's Pack"
author = "Circle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71aa107cd5019a7073ec7acbfd10ba494f895cda18cc571dfc08c53c625cb18d"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.3"
