name = "Circle's Pack"
author = "Circle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78c962a0672647a5de0006079b99dd2add5cdb947f1d77bd3f8599a7c42d9b2a"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
