name = "Circle's Pack"
author = "Circle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "877fca1f5a1f5ac511f04fd888d1be6718ec68297ffa132d4a83042044e72f10"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"
