name = "Circle's Pack"
author = "Circle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6d72e0cc5701b532287494e7be45fb2fe5fe0823a536ee036eefe9f8209b1ef"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.3"
