name = "Circle's Pack"
author = "Circle"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1665bd31ef95466a683223f5151cb62f0796d0f65e96a4f778caa71eb733d234"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.3"
